### PR TITLE
Function serialization

### PR DESCRIPTION
**Pull request by FrigoEU**
Hey,

So I've come up with a way to support, or rather simulate some kind of function serialization. I've tried to make it as general as possible.

Basically I've added support for two functions: in toJson I've added the serializeFunction argument and threaded it all the way through. This argument should be a function that gets called whenever we find a function in a properties object. We call this function with the key (eg: "onclick") and the value (the actual function), and expect an array with two elements back, the key (eg: "onclick") and the value of the property (eg: a sequence number). The value then gets "_vdom_as_json_" prepended to it, and this will get sent over the wire.

So if you have a properties object like this: 
{ onclick: myfunc }

The serializeFunction will get called with "onclick" and myfunc as arguments. If that serializeFunction then returns ["onclick", 1], the properties object that will be returned by toJson will be {onclick: "_vdom_as_json_1"}.

At the other side, fromJson takes an argument "makeHandler" (not sure about the name). This is a function that will be called when we detect a property with value "_vdom_as_json_<something>". This function will be called with <something>. So in our above example that would be "1". This makeHandler function should then return a function that will be used as the event handler for that property (in our example that's "onclick").

Ok, I hope this whole explanation is clear... I don't expect this PR to be accepted right away since it doesn't add any tests nor does it add the necessary documentation, but I'd rather have you take a look at it first to see what you think.

The tricky part with this whole serialization stuff is that you'd sometimes like event handlers on the main thread to do stuff, like for example grab the pageX and pageY properties of the event. How you'd be able to "encode" this into this solution would be something like this:
- 1. In your VTree you'll make a properties object like this 

```
{ onclickxy: function(xAndY){...} }
```
- 2. Your serializeFunction can then be:

```
var nextIndex = 0;
var functionMap = {};
function serializeFunction(key, func){
  functionMap[nextIndex] = func;
  if (key === "onclickxy"){
    return [“onclick", "#" + nextIndex + "@" + "xy"; 
  }
  nextIndex = nextIndex + 1;
}
```

(I have a more sophisticated version of this, kept short for clarity)
- 3. Your makeHandler function:

```
var regex = /#(\d+)@(.*)/;
function makeHandler(str){
  var matches = str.match(regex), nr = matches[1], serialized = matches[2];

  if (serialized === "xy"){
    return function(ev){
      message = {nr: nr, data: {x: ev.pageX, y: ev.pageY}};
      worker.postMessage(JSON.stringify(message));
    };
  }
}
```
- 4. At the worker side you could then have something like this: 

```
onmessage = function(m){
  var message = JSON.parse(m.data);
  functionMap[message.id](message.data);
};
```

Ok this was long, hope you can do something with. Let me know if I can do anything to clarify/improve!

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for opening this PR, and for the discussion! For this particular PR, I agree that I can't really merge this without any new tests; that would be step 1.

As for serializing functions themselves, I think it miiiiight be possible if we added [lave](https://www.npmjs.com/package/lave) as a dependency, since it's explicitly meant to handle tricky things like functions. However, I'm not sure how exactly how much it can serialize in the case of onclick listeners; you might want to try it out in your case and see if it fits.

That said, if you can get this working with some set of arbitrary functions, and add some tests to demonstrate that the functions are doing what you expect them to do, then yeah I'd be happy to merge. :)

**Comment by bloodyKnuckles** [comment]
I learned of this pull request on the live OSS hacking video yesterday. Caught the last hour.

My experience with function serialization, on an exploratory project here:

https://github.com/bloodyKnuckles/patchdom

...is that functions don't pass the Web Worker thread barrior. `vdom-as-json` and `vdom-serialized-patch` simply replace the function with an empty object. What I came up with is to `toString` the function on one end and `eval` it on the other end.

[Forked `vdom-as-json`](https://github.com/bloodyKnuckles/vdom-as-json)

[vdom-as-json/lib/toJson.js ln:109](https://github.com/bloodyKnuckles/vdom-as-json/blob/master/lib/toJson.js#L109-112), I added a function check and am converting it to a string.

```
    case 'function':
      return obj.toString();
      break;
```

[vdom-as-json/lib/fromJson.js ln:25](https://github.com/bloodyKnuckles/vdom-as-json/blob/master/lib/fromJson.js#L25-35), I'm looking for a string and checking if the string starts with "function", if so, `eval`ing string to return the function.

```
    if (
      'string' === typeof json[key]
      && 0 === key.indexOf('on')
      && 0 === json[key].indexOf('function ')
    ) {
      res[key] = eval('(' + json[key] + ')');
    }
    else {
      var val = json[key];
      res[key] = typeof val !== 'undefined' ? fromJson(val) : val;
    }
```

[Working patchdom demo.](http://bloodyknuckles.neocities.org/patchdom/)

I'm concerned about the security weaknesses of `eval` but am not aware of any opportunities for malicious code to get snuck in. Another problem, the check for a string starting with function means that no legitimate strings starting with the word "function" will get through. A little more robust function formatting check improves on this problem.

**Comment by nolanlawson** [comment]
@bloodyKnuckles Yep, `function.toString()` and `eval()` are a pretty good solution to this problem, although they don't handle every case (e.g. closures that refer to a variable outside of the function). I believe `lave` might actually have some tricks that help is catch some of these issues, but I'm not sure TBH.

**Comment by nolanlawson** [comment]
Closing, please reopen if you have time to fix failing tests and respond to issues I raised in the review, thanks so much for opening the PR and please don't hesitate to fork if you absolutely need this feature, cheers

**Pull request closed without merging**
